### ISSUE TITLE
Fraction Digits Capped at 9

### ISSUE THREAD

**Issue by PrestonMonteWest** [dev4Agriculture/isoxml-js#20]
I was curious why a lot of the xs:decimal attributes are capped at 9 fractional digits? I need to be able to send higher precision latitude, longitude, and altitude values, but I'm running into this restriction. Would it be possible to have a more precise Point entity?

Thanks for any clarification!

**Comment by aparshin** [comment]
@PrestonMonteWest, 9 fractional digits of WGS-84 coordinates gives you precision of ~0.11 **mm** (and even less for longitude outside equator). It should be enough for most agriculture tasks. I don't know the exact reason of this limitation in XSDs of the standard, but my guess is that it might be related to hardware limitations of controllers or it can be some kind of optimization of ISOXML file size...

Do you really have a use case where 0.11 mm is not enough?

**Comment by PrestonMonteWest** [comment]
@aparshin Okay, that's completely fair. I'm exporting data from a system that stores coordinates using more decimal places, so I wanted to try to avoid data loss. But sub-mm accuracy will definitely suffice! Do you have a link to the specific part of WGS-84 that defines 9 fraction digits? That would be awesome if so.

**Comment by PrestonMonteWest** [comment]
@aparshin Never mind the last question. I found it. I do have another question though. It looks like the fraction digits restriction was added to a newer version of the ISOXML standard. I also see that a version can be passed to the ISOXMLManager constructor, so would passing version 3 instead of 4 disable the fraction digits restriction in the library? It's fine if it doesn't, just curious.

**Comment by aparshin** [comment]
@PrestonMonteWest Yes, you are right, this restriction is missing in ISOXML v3 XSDs. But, unfortunately, such differences in versions are ignored in ISOXML.js, the only changes to take into consideration are new attributes and new entities. So, if you switch to V3 in `ISOXMLManager` constructor, the restriction will be still applied.

**Comment by PrestonMonteWest** [comment]
Not a problem. Like you said, ~0.11 mm is definitely enough (even enough to find a grain of sand according to XKCD!). Taking all that into account, I'll close this issue. Thanks again for the clarification!
